### ISSUE TITLE
Error trying to register an account on mud.molylepke.hu

### ISSUE THREAD

**Issue by nguyenhuy-hoanganh** [zbylyrcxr/DennisMUD#3]
I tried to create an account with `register Username Password` , but it output this result:

```
Traceback (most recent call last):
  File "/home/deyurn/zschokkei_mud/lib/telnet.py", line 206, in lineReceived
    self.factory.router.shell.command(self.factory.router[self.peer]["console"], line)
  File "/home/deyurn/zschokkei_mud/lib/shell.py", line 230, in command
    return self.call(console, ' '.join(line[:-splitpos]), line[-splitpos:])
  File "/home/deyurn/zschokkei_mud/lib/shell.py", line 597, in call
    return self._commands[command].COMMAND(console, args)
  File "/home/deyurn/zschokkei_mud/commands/register.py", line 100, in COMMAND
    "enabled": console.database.defaults["users"]["keepalive"]["enabled"]
KeyError: 'keepalive'
```
Is it still too early to be able to register and try out the game?

**Comment by zbylyrcxr** [comment]
Sorry I didn't really pay much attention to the place because of irl stuff, it's a silly bug I'll fix asap.
